### ISSUE TITLE
Can you set the background colour of minimap?

### ISSUE THREAD

**Issue by parndt** [JulianEberius/Textmate-Minimap#15]
I want to be able to change the background colour of the minimap from black to something else. My screen is quite tall and so when I open files that don't use up the entire minimap space I want to be able to change the background colour of the container from the standard (#000000 black) to something else. This is because I often have windows behind Textmate e.g. Terminal which have a black background and it leads to confusion. (My Textmate colour scheme uses a white background)

Am I missing a setting somewhere that lets me do this or is this yet to be implemented? Thanks.

**Comment by JulianEberius** [comment]
Never really noticed this problem (My theme has a black background).
So this is really not implemented, but should not be a difficult problem. I will post here when a solution is in the repository.

**Comment by parndt** [comment]
Nice one, thanks!

**Comment by lehni** [comment]
What if it was a slightly darker shade of the background color by default? Like this, black would remain black, and white would become a slight gray.

**Comment by parndt** [comment]
I think it should correspond to the background colour that the Textmate user has set up in their Textmate. Maybe future versions would allow you to pick it but IMHO it should correspond to the set background colour if the UI is to be cohesive.

**Comment by JulianEberius** [comment]
That's how I implemented it just now. It's not released as of now (I want to finish integrating Sparkle for auto-updating) but will be soon.

**Comment by parndt** [comment]
Thanks, Julian. Look forward to it.

**Comment by JulianEberius** [comment]
Fixed in 0.61!
