### ISSUE TITLE
Clicking on the minimap doesn’t select the text visible *at that location*

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [JulianEberius/Textmate-Minimap#20]
If the minimap is shorter than the height of the available space for it, then clicking anywhere on the minimap becomes out‐of‐sync with the actual target of the click: the position in the document of the click seems to be proportional to the visible area as if the minimap were the exact height of the window, not the actual height it is.

For instance, if the minimap is only taking up 50% of the height of the window, and I click on the middle of the document as it is displayed in the minimap… the _actual selection point_ in the document ends up being a quarter of the way through it; because the position I clicked was 25% down the visible height of the window.

**Comment by JulianEberius** [comment]
Thanks for your report. In fact you're not even the only one to report it, someone already mailed me about this. I hope I will find some time to fix it in the next days (I think it should be an easy fix...)

**Comment by ELLIOTTCABLE** [comment]
Thanks! Were I a little less busy with [Paws](/elliottcable/Paws.o) I’d have just forked it and fixed it myself. I’m glad you’re already looking into it though :O

**Comment by JulianEberius** [comment]
Published version 0.72 that fixes the problem.

p.s. noticed that this still does not work when "soft wrap" is active... but that would be a harder fix.

**Comment by ELLIOTTCABLE** [comment]
Awesome! I don’t really care about soft wrap; I’ll close this and let you open a new issue for that, if you want. :3
