### ISSUE TITLE
Crop the minimap horizontally

### ISSUE THREAD

**Issue by int3h** [JulianEberius/Textmate-Minimap#24]
In code with really long lines, minimap renders the whole document (well past what the current viewport can see) and then squishes this horizontally to fit the minimap viewport. This results in a really blurry, hard-to-see minimap.

It would be nice if minimap cropped the minimap view to only show what the current text view can see, horizontally. Failing that, simply having a scaling factor to determine the maximum allowable width would be nice. (That is, if n lines are shown in the minmap, the minimap is cropped at n*k pixels in width -- before scaling, of course.)

**Comment by JulianEberius** [comment]
Thanks for the idea. Seems very logical, I don't know why this isn't already in there^^ 
I'll look into it the next time I have spare time for TM-Minimap.

**Comment by malvese** [comment]
Great idea. That way we could keep the same proportions as the original. I've found it much easier to find a specific piece of code in the minimap if it really looks like the fullsize one. If it's strecthed it's harder to recognize.

**Comment by JulianEberius** [comment]
This has been fixed in version 0.73. Just hit update in Preferences -> Minimap!
