### ISSUE TITLE
Selecting/Highlighting text through 'Find Next' doesn't reflect on the MiniMap 

### ISSUE THREAD

**Issue by arthur5005** [JulianEberius/Textmate-Minimap#25]
When using 'Find', Textmate changes what's selected, but Minimap doesn't update that until you hit escape twice, once for the 'Find' window a second time seems to update the Minimap finally.

Same goes with 'Command-E' and 'Command-G' on selected text. 'Command-G' (Find Next) traverses the document and selects the next occurrence of what was selected using 'Command-G', but Minimap doesn't update to reflect this selection change until you hit escape (in this case it's only required to press escape once).

Just as a side note:
The ultimate implementation of Minimap imho would be to use this in order to see all occurrences of a specific word in the current document. Unfortunately Textmate is missing the 'highlight all occurrences of the current selection' feature, that editors like Notepad++ have. This feature combined with Minimap would be a real boon to the community.

At the very least it would be great if 'Command-E' -> 'Command-G' was working with Minimap, it would be a step in the right direction.

**Comment by JulianEberius** [comment]
This has been fixed in version 0.73. Just hit update in Preferences -> Minimap!

**Comment by arthur5005** [comment]
Too awesome! Works great! Thanks!

**Comment by JulianEberius** [comment]
I'm happy that you are happy even after waiting 4 months for it ;-)
