### ISSUE TITLE
Code is not displayed

### ISSUE THREAD

**Issue by primalmotion** [JulianEberius/Textmate-Minimap#27]
When using MiniMap last master rev, TM launches fine, but when I select a code file (Objective-J), I got nothing displayed. There are the scrollers, but the main view keeps displaying the big textmate icon.

I use the following plugins:
- EGOTextMateFullScreen
- GetBundles
- MissingDrawer
- ProjectPlus

Thanks,

**Comment by JulianEberius** [comment]
Hi,

I'm sure it is an unwelcome interaction with MissingDrawer or EGO... It should be compatible with ProjectPlus.
I'll write again when I find time to check the two other plugins out.

Greetings,
Julian

**Comment by primalmotion** [comment]
Hi,

Actually no, I try to remove one by one the plugins and try several config.
The culprit is still Project Plus. Also I notice that when minimap is loaded, is overrides the MissingDrawer background color (i.e. it is white)

I can provide you any information you'll need.

Thanks,
