### ISSUE TITLE
Performance issues with bigger documents

### ISSUE THREAD

**Issue by JulianEberius** [JulianEberius/Textmate-Minimap#3]

**Comment by JulianEberius** [comment]
Situation has improved a lot in version 0.7

**Comment by 4rc0s** [comment]
I just had TM crash after very high CPU on a large document. Suspect Minimap.

Crash dump: http://gist.github.com/369924

**Comment by JulianEberius** [comment]
Yeah, definitely a Minimap issue. Thanks for the dump, I'll look into it.
