### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by mwarkentin** [JulianEberius/Textmate-Minimap#4]
When I try to download any of the files in Downloads, I get the following error message:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>82EB365CE922039D</RequestId>
−
<HostId>
09TGJ1F+57xbBTP/EW+1LzU4awpGMgoPYi2uAo1u6vxOoKfVX1iVQKG/WxzkPme9
</HostId>
</Error>

**Comment by JulianEberius** [comment]
Just confirmed your issue. Seems like a GitHub issue to me (I didn't change anything :-) )
Just re-uploaded the file, and it works again...

**Comment by mwarkentin** [comment]
Yep, works!  Thanks. :)
