### ISSUE TITLE
Git clone link on website is wrong

### ISSUE THREAD

**Issue by soffes** [JulianEberius/Textmate-Minimap#5]
The website has `git://github.com/julianEberius/Textmate-Minimap.git` as the download link. It should be `git://github.com/JulianEberius/Textmate-Minimap.git`. Notice the `J` in the username.

**Comment by JulianEberius** [comment]
Thanks for the notice. I changed my username from "julianEberius" to "JulianEberius". Of course the page is "hard-coded", and does not update automatically ;-)

**Comment by soffes** [comment]
No problem. Very cool plugin. Thanks!
