### ISSUE TITLE
Open on left option

### ISSUE THREAD

**Issue by tekkub** [JulianEberius/Textmate-Minimap#6]
I have my drawer on the right, and I like having it there.  Can we have an option somewhere so that the map can be opened on the left instead?

**Comment by jerodsanto** [comment]
Even better: detect which side the drawer is open on and open the opposite side.

**Comment by valo** [comment]
There is a workaround for this. What I did is to move the window next to the left edge of the monitor. When the drawer is shown it will show on the right side. After that move the window to the left side of the monitor and show the minimap. It will show to the left.

**Comment by JulianEberius** [comment]
I'm going to implement a preference pane similar to how ProjectPlus does it. 
I think it will contain three modes: auto (the side the project drawer is not on), left and right. 
I will post here and close this issue when this is done.

**Comment by tekkub** [comment]
That workaround works, but when you close the project and reopen it you have to do it again.  The "auto" mode you propose would be a great default.

**Comment by JulianEberius** [comment]
should be fixed in release 0.6

**Comment by tekkub** [comment]
And it works, sweeeet
