### ISSUE TITLE
closing Textmate window doesn't send buffer output to a waiting Terminal process

### ISSUE THREAD

**Issue by fermion** [JulianEberius/Textmate-Minimap#7]
Firstly, this is an awesome plugin — great idea, great work so far.

I've found a deal breaker (for now) issue.  I use Textmate for reviewing git commit lists and entering comments.  When closing the temporary window Textmate usually sends buffer output to Terminal thus proceeding with the commit, etc.  This plugin, for some reason, breaks that flow.

If I knew any Objective-C at all I'd just patch and commit this, thanks again for the sweet idea/plugin.

**Comment by valo** [comment]
Same problem here. I am using textmate for entering commit messages when committing with git. The plugin breaks that. The "git commit" command waits forever after the textmate window is closed.

**Comment by JulianEberius** [comment]
Should be fixed in the current repository version. There was a memory leak, keeping the window open "in the background" when it is closed. 
If you want the fix now, compile the repo-version with XCode. I will upload a new release when the preference window is finished (issue #6).

**Comment by JulianEberius** [comment]
should be fixed in release 0.6

**Comment by fermion** [comment]
Thanks Julian!

**Comment by grimen** [comment]
A-W-E-S-O-M-E
